### ISSUE TITLE
Allow users to see all rep of user on seperate page

### ISSUE THREAD

**Issue by bustapaladin** [FinlayDaG33k/MaidBot#18]
What is rep for if one cannot see the user his rep points and comments from whom he got them or for someone else to see how legit he is?

Show all rep of a user in a nice table column with headings as Rep Date, Rep comment, from whom, + or -
on a page for the user in question.

EG https://maidbot.finlaydag33k.nl/paladin

**Comment by FinlayDaG33k** [comment]
Sorta fixed now :) 
Will work on improving it, but the basics are there.
